### ISSUE TITLE
Better handling of errors when we can't write to tmp path

### ISSUE THREAD

**Issue by obromios** [rails/spring#127]
Running on Unbuntu 12.04 guest on a window 7 machine using virtua box. If I start spring I receive the error message below.  I am running Ruby 1.9.3p392 (2013-02-22 revision 39386) [i686-linux] and rails 3.2.12. I have tried deleting the spring.pid file, but this does not help.

```
/home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:85:in `unlink': Text file busy - /media/sf_Sites/rails_projects/mentor/tmp/spring/spring.pid (Errno::ETXTBSY)
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:85:in `unlink'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:85:in `block (2 levels) in set_exit_hook'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:84:in `each'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:84:in `block in set_exit_hook'
/home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:34:in `initialize': Operation not permitted - "/media/sf_Sites/rails_projects/mentor/tmp/spring/spring" (Errno::EPERM)
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:34:in `open'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:34:in `boot'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/server.rb:15:in `boot'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/client/start.rb:13:in `call'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/client/command.rb:7:in `call'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/lib/spring/client.rb:23:in `run'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/gems/spring-0.0.8/bin/spring:4:in `<top (required)>'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/bin/spring:19:in `load'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/bin/spring:19:in `<main>'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/chris/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by frankie-loves-jesus** [comment]
Normally I use BSD where everything works great, but right now I'm forced by my VPS to use Ubuntu where I'm getting a similar error:
```
% bundle exec rake db:reset RAILS_ENV=production
/usr/local/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /run/user/1000/spring (Errno::EACCES)
```

I had to `sudo chmod -R 1777 /run/user/1000/` to fix it, but I'm not sure how comfortable I am changing write permissions on system dirs like that.

Ref.: http://stackoverflow.com/questions/23822491/ruby-on-rails-permission-denied-when-using-rails-generate-controller-welcome
