### ISSUE TITLE
"prepare called on a closed database" at the first access to DB in rspec

### ISSUE THREAD

**Issue by tomykaira** [rails/spring#134]
When I run `bundle exec spring rspec spec/models/user_spec.rb`, I got the following trace.

What I tried
- re-create test db (in vain)
- restart spring server, restart machine (in vain)
- run without spring (no error occurred)
- run without file specification (no error occurred)
- try other spec files (the same, if it need to access DB)

It seems that this error occurs at the first access to DB.

I found that this patch fixes the problem, but obviously not correct answer.

``` ruby
# activerecord-3.2.13/lib/active_record/fixtures.rb
        @fixture_connections.each do |connection|
          if connection.open_transactions != 0
            unless (connection.raw_connection.closed?) # add this block
              connection.rollback_db_transaction
              connection.decrement_open_transactions
            end
          end
        end
```

My OS is Ubuntu 12.04, 32 bit.

Any information is appreciated.

```
 Failure/Error: Unable to find matching line from backtrace
 ActiveRecord::StatementInvalid:
   ArgumentError: prepare called on a closed database: rollback transaction
 # .bundle/gems/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `initialize'
 # .bundle/gems/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `new'
 # .bundle/gems/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `prepare'
 # .bundle/gems/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:134:in `execute'
 # .bundle/gems/ruby/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:515:in `rollback'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/sqlite_adapter.rb:322:in `block in rollback_db_transaction'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
 # .bundle/gems/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/sqlite_adapter.rb:322:in `rollback_db_transaction'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/fixtures.rb:880:in `block in teardown_fixtures'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/fixtures.rb:878:in `each'
 # .bundle/gems/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/fixtures.rb:878:in `teardown_fixtures'
 # .bundle/gems/ruby/1.9.1/gems/rspec-rails-2.13.0/lib/rspec/rails/adapters.rb:62:in `block (2 levels) in teardown'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:470:in `instance_eval'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:470:in `instance_eval_with_rescue'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:242:in `instance_eval_with_rescue'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:31:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `each'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:66:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:418:in `run_hook'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:339:in `run_after_each_hooks'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:304:in `run_after_each'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:120:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:179:in `call'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:179:in `run'
 # spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:87:in `block (2 levels) in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:85:in `call'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:85:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/hooks.rb:418:in `run_hook'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:329:in `run_around_each_hooks'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:256:in `with_around_each_hooks'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:111:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:390:in `block in run_examples'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `map'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `run_examples'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:371:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `map'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:34:in `report'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25:in `run'
 # .bundle/gems/ruby/1.9.1/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/commands.rb:110:in `call'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:71:in `block in serve'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:66:in `fork'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:66:in `serve'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:49:in `block in run'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:43:in `loop'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:43:in `run'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application.rb:37:in `start'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:95:in `block in start_child'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:82:in `fork'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:82:in `start_child'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:27:in `start'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:54:in `block in with_child'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:21:in `synchronize'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:43:in `with_child'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/application_manager.rb:62:in `run'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/server.rb:47:in `serve'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/server.rb:35:in `block in boot'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/server.rb:35:in `loop'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/server.rb:35:in `boot'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/server.rb:15:in `boot'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/client/start.rb:13:in `call'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/client/command.rb:7:in `call'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/lib/spring/client.rb:23:in `run'
 # .bundle/gems/ruby/1.9.1/gems/spring-0.0.8/bin/spring:4:in `<top (required)>'
 # .bundle/gems/ruby/1.9.1/bin/spring:23:in `load'
 # .bundle/gems/ruby/1.9.1/bin/spring:23:in `<main>'
```

**Comment by zulhfreelancer** [comment]
Upgrading to `gem 'spring', '~> 2.0', '>= 2.0.1'` solve this problem. Thanks @jonleighton.
