### ISSUE TITLE
Spring not working fast enough with an engine

### ISSUE THREAD

**Issue by davidmles** [rails/spring#316]
Spring is not working well (fast) enough when developing an engine.

Steps to reproduce:

```
rails plugin new example --mountable
cd example/
echo "gem 'spring'" >> Gemfile
bundle
echo "Spring.application_root = './test/dummy'" > config/spring.rb
bundle exec spring binstub --all
```

Running default tests takes more than 2 seconds:

```
david$ time spring rake test
Run options: --seed 23128

# Running:

.

Finished in 0.003607s, 277.2387 runs/s, 277.2387 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real    0m2.737s
user    0m0.091s
sys 0m0.048s
```

Running it again still takes more than 1 second:

```
david$ time spring rake test
Run options: --seed 57874

# Running:

.

Finished in 0.003406s, 293.5995 runs/s, 293.5995 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real    0m1.427s
user    0m0.093s
sys 0m0.042s
```

I would also note that I'm using rbenv.

**Comment by davidmles** [comment]
This is still happening on Rails 4.2 although now it displays some errors:

```
example david$ time spring rake test
/Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
/Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/configuration.rb:31:in `application_root_path': Spring::MissingApplication (Spring::MissingApplication)
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:246:in `loaded_application_features'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:105:in `ensure in preload'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:112:in `preload'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/david/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
Run options: --seed 42763

# Running:

.

Finished in 0.003399s, 294.2042 runs/s, 294.2042 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real	0m2.388s
user	0m0.093s
sys	0m0.036s
```
