### ISSUE TITLE
Exception on assets tasks

### ISSUE THREAD

**Issue by p0deje** [rails/spring#360]
Assets tasks are crashing:

```bash
$ rake assets:clean
/Users/p0deje/.rbenv/versions/2.0.0-p451/bin/ruby rake assets:clean assets:clean:all RAILS_ENV=development RAILS_GROUPS=assets
/Users/p0deje/.rbenv/versions/2.0.0-p451/bin/ruby: No such file or directory -- rake assets:clean (LoadError)
rake aborted!
Command failed with status (1): [/Users/p0deje/.rbenv/versions/2.0.0-p451/b...]
./vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:12:in `ruby_rake_task'
./vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
./vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:80:in `block (2 levels) in <top (required)>'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
./vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
-e:1:in `<main>'
Tasks: TOP => assets:clean
(See full trace by running task with --trace)
```

`bundle exec rake assets:clean` however works correctly.

Ruby: 2.0.0-p451
Rails: 3.2.19
Spring: 0.9.1

**Comment by sonalkr132** [comment]
hi @p0deje Can you help me reproduce this? I did (using spring 1.6.2):

```
$ spring status
8295 spring server | <app> | started 38 secs ago
8298 spring app    | <app> | started 38 secs ago | development mode
$ rake assets:precompile
. . .
$ rake assets:clean
```
I didn't get any error. Besides, I don't see how is this related to spring.

**Comment by p0deje** [comment]
No longer can reproduce it as well. Guess it's fixed already.
