### ISSUE TITLE
Spring is not working with non-UTF8 environments

### ISSUE THREAD

**Issue by ZipoKing** [rails/spring#363]
In my Linux machine (using Rails 4.1.7 with Ruby 2.1.5) I'm using ISO-8859-2 character encoding. I have found, that if there is some environment variable set which is using non-ASCII character (encoded in ISO-8859 and not in UTF-8) then Spring raises an exception during start:

```
/usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:305:in `match': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:305:in `strtok'
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:275:in `tok'
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:238:in `lex'
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:69:in `decode'
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:17:in `load'
        from /usr/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application/boot.rb:8:in `<top (required)>'
        from /usr/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by josephecombs** [comment]
I have the same issue with this error, but it seems to only happen randomly.   As in, I open another zsh window and I get the error running a command that works just fine in the other window.  Here's my error:

/Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:305:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:305:in `strtok'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:275:in `tok'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:238:in `lex'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:69:in `decode'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/json.rb:17:in `load'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application/boot.rb:8:in `<top (required)>'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jcombs/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by josephecombs** [comment]
I may have just resolved this - I had two versions (1.1.3 and 1.2.0) of Spring installed and my project was referencing the older version.  I updated Gemfile.lock to reference the newer version and things started working.
