### ISSUE TITLE
Something wrong with shush backtraces

### ISSUE THREAD

**Issue by edbond** [rails/spring#375]
Doing a `User.first.destroy` in rails console results in:

```
Exception: NoMethodError: undefined method `reject!' for nil:NilClass
--
 0: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:269:in `ensure in block (2 levels) in shush_backtraces'
 1: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:269:in `block (2 levels) in shush_backtraces'
 2: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:212:in `rescue in within_new_transaction'
 3: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:220:in `within_new_transaction'
 4: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
 5: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'
 6: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
 7: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activerecord-4.1.7/lib/active_record/transactions.rb:263:in `destroy'
 8: (pry):1:in `__pry__'
 9: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
10: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
11: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
12: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
13: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
14: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
15: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
16: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
17: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
18: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
19: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
20: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
21: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
22: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
23: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
24: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
25: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
26: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
27: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
28: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
29: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
30: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
31: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
32: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
33: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
34: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
35: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
36: /home/eduard/stocktalk/bin/rails:8:in `<top (required)>'
37: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
38: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
39: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
40: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
41: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
42: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
43: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
44: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
45: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
46: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
47: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
48: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
49: /home/eduard/.rvm/gems/ruby-2.1.4@stocktalk/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
50: /home/eduard/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
51: /home/eduard/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
52: -e:1:in `<main>'
```

**Comment by sonalkr132** [comment]
@edbond Can you please give a bit more detailed description of recreating this issue?

**Comment by edbond** [comment]
I can't reproduce it anymore. Maybe the problem was in my code.
