### ISSUE TITLE
Spring errors out when typing `spring`

### ISSUE THREAD

**Issue by rodrigoargumedo** [rails/spring#411]
I found a strange error bug that Spring is not running from Windows command lines (PowerShell and cmd) that it doesn't request the proper files to run Spring.

```
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/sid.rb:33:in ``': No such file or directory - ps -p 7420 -o sess= (Errno::ENOENT)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/sid.rb:33:in `sid'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/sid.rb:39:in `pgid'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/server.rb:78:in `set_pgid'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/server.rb:34:in `boot'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/server.rb:14:in `boot'
        from -e:1:in `<main>'
```

I confirmed this error in v1.3.6 and v1.3.5. I'm not really sure this affects certain Windows users but I couldn't reproduce this bug in Mac or Linux.

**Comment by rafaelfranca** [comment]
spring doesn't work on windows machines because it don't support `Process.fork`
