### ISSUE TITLE
Spring v1.6.1 broken on Ruby 2.3.0

### ISSUE THREAD

**Issue by kirs** [rails/spring#461]
```
spring stop && bin/spring rails console
Spring stopped.                    ⇣
/Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/commands.rb:34:in `<module:Spring>'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application.rb:77:in `preload'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application.rb:143:in `serve'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application.rb:131:in `block in run'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application.rb:125:in `loop'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application.rb:125:in `run'
	from /Users/kir/Projects/project/vendor/bundle/ruby/2.3.0/gems/spring-1.6.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kir/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by sonalkr132** [comment]
Duplicate of #456

**Comment by kirs** [comment]
Thanks!
