### ISSUE TITLE
Unable to start rails console

### ISSUE THREAD

**Issue by c0mrade** [rails/spring#464]
I m unable to start `rails console` while having gem spring in the gem file. This is the error I get :

```
±  |master ✗| → bin/rails console
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-6.0.2 because its extensions are not built.  Try: gem pristine byebug --version 6.0.2
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
Ignoring passenger-5.0.23 because its extensions are not built.  Try: gem pristine passenger --version 5.0.23
Ignoring pg-0.18.3 because its extensions are not built.  Try: gem pristine pg --version 0.18.3
Ignoring sqlite3-1.3.10 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.10
Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
/Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/commands.rb:33:in `<module:Spring>'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application.rb:77:in `preload'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application.rb:143:in `serve'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application.rb:131:in `block in run'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application.rb:125:in `loop'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application.rb:125:in `run'
	from /RDX/dc/vendor/bundle/gems/spring-1.6.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/c0mrade/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Using spring `1.6.1` like you can see from the logs. I can't load my console if I only stop spring `bin/spring stop` from running. I have to also remove it from my Gemfile and do a `bundle install`. I m using rails `4.2.5`

Am I doing something wrong here?

**Comment by morgoth** [comment]
Looks like a duplicate of https://github.com/rails/spring/issues/456

**Comment by c0mrade** [comment]
@morgoth yes it's a duplicate didn't see that one. closing
