### ISSUE TITLE
rails generate controller fails when using bundler

### ISSUE THREAD

**Issue by fschwan** [rails/spring#465]
reproduction:
ruby: 2.3.0p0
bundler: 1.11.2

```
mkdir testapp
cd testapp
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'rails'" >> Gemfile
bundle install --path vendor/bundle
bundle exec rails new .
```
Overwrite Gemfile? -> Yes
```
bundle exec rails g controller con view
```
leads to:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/commands.rb:33:in `<module:Spring>'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/commands.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:77:in `preload'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /home/user/testapp/vendor/bundle/ruby/2.3.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Fix:
Do not use spring.

This bug is related:
https://github.com/bundler/bundler/issues/4165#issuecomment-170393820

The issue seem to be some env vars...?

**Comment by sonalkr132** [comment]
Probably we don't need this, since #456 has been reopened.

**Comment by fschwan** [comment]
Closing this in favor of #456
