### ISSUE TITLE
Rails Generate commands not working with Spring 1.7.0

### ISSUE THREAD

**Issue by catob** [rails/spring#478]
I created a new app today right after the 1.7.0 release and I'm getting this error message when I try to generate a new controller: 

```
/Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/run.rb:72:in `spawn': No such file or directory - spring (Errno::ENOENT)
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/run.rb:72:in `boot_server'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/run.rb:53:in `cold_run'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/run.rb:30:in `rescue in call'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/run.rb:27:in `call'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/command.rb:7:in `call'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/rails.rb:24:in `call'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client/command.rb:7:in `call'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/client.rb:30:in `run'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/bin/spring:49:in `<top (required)>'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/binstub.rb:11:in `load'
	from /Users/catobenjaminsen/work/testapp/.bundle/gems/spring-1.7.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/catobenjaminsen/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/catobenjaminsen/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/catobenjaminsen/work/testapp/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

My spring was not running, and I got the same error message when running `bin/spring start`

At the time I was running ruby 2.1.1p76. I updated to ruby 2.3.0, but I was still getting the same error message. After a while I tried to run my bundle with: `gem 'spring', '~> 1.6.4'` and my generate commands are working again.

Are anyone else experiencing the same kind of issues with the new release or is it just me?

**Comment by morgoth** [comment]
I have exactly the same issue when running my tests on Travis

**Comment by jonleighton** [comment]
Do you still have problems with version 1.7.1?

**Comment by catob** [comment]
Everything is working with 1.7.1. Thanks!
