### ISSUE TITLE
Spring can't find bundler version 1.12

### ISSUE THREAD

**Issue by KazuyaHara** [rails/spring#481]
When I run testing with rspec, guard, spring and bundler 1.11.2, it works fine. But with bundler 1.12.3, it doesn't work and I got the error message as below.

```
# using bundler 1.12.3
Kazuya:my-project kazuya$ bundle -v
Bundler version 1.12.3

# and then I ran testing with rspec & guard ...
Kazuya:my-project kazuya$ bundle exec guard
16:06:18 - INFO - Guard::RSpec is running
16:06:19 - INFO - Guard is now watching at '/path/to/project'
[1] guard(main)> 
16:06:21 - INFO - Run all
16:06:21 - INFO - Running all specs

# got this message
/Users/kazuya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 194 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/kazuya/path/to/project/vendor/bundle/ruby/2.3.0', execute `gem env` for more information
    from /Users/kazuya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /Users/kazuya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /Users/kazuya/.rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
16:06:21 - ERROR - Failed: "bundle exec spring rspec -f d -r /Users/kazuya/path/to/project/vendor/bundle/ruby/2.3.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec" (exit code: 1)
```

**Comment by theIntuitionist** [comment]
Thanks for this report. for now, i am just downgrading bundler.
