### ISSUE TITLE
start rails server, or migrations or generates, spring errors up

### ISSUE THREAD

**Issue by eoinshea** [rails/spring#502]
# When i run rails s:

/home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load': 
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:87: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
              when Fixnum.name: 'val.to_s.empty? ? nil : val.to_i'
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:88: syntax error, unexpected keyword_when, expecting keyword_end
              when String.name: 'val.to_s'
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:88: syntax error, unexpected ':'
              when String.name: 'val.to_s'
                               ^
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:89: syntax error, unexpected keyword_when, expecting keyword_end
              when Float.name: 'val.to_f'
                  ^
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:89: syntax error, unexpected ':'
              when Float.name: 'val.to_f'
                              ^
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:90: syntax error, unexpected keyword_when, expecting keyword_end
              when Time.name: 'val.is_a?(Hash) ...
                  ^
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:90: syntax error, unexpected ':'
              when Time.name: 'val.is_a?(Hash) ? Time.loca...
                             ^
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:91: syntax error, unexpected keyword_when, expecting keyword_end
              when Date.name: 'val.is_a?(Hash) ...
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:91: syntax error, unexpected ':'
              when Date.name: 'val.is_a?(Hash) ? Time.loca...
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:92: syntax error, unexpected keyword_when, expecting keyword_end
              when TrueClass.name, FalseClass.n...

/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:92: syntax error, unexpected ':', expecting &. or :: or '[' or '.'
...rueClass.name, FalseClass.name: 'val == "on" or val == "true...
/home/eoin/.rvm/gems/ruby-2.3.1/gems/glue-0.41.0/lib/glue/attribute.rb:113: syntax error, unexpected keyword_end, expecting end-of-input
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
        from /home/eoin/.rvm/gems/ruby-2.3.1/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/eoin/RubymineProjects/TwitterSentiment/bin/spring:14:in `require'
        from /home/eoin/RubymineProjects/TwitterSentiment/bin/spring:14:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

**Comment by eoinshea** [comment]
it was fixed but i cant remember, as usual probably my code/setup
