### ISSUE TITLE
`spring` fails if the gem is bundled using `path:`

### ISSUE THREAD

**Issue by dadooda** [rails/spring#539]
Hey team,

Here's an issue. Current version is 2.0.2, full-repo clone to `vendor/gems/spring` (see below).

`Gemfile`:

```
group :development do
  gem "spring", path: Pathname(__dir__).realpath + "vendor/gems/spring"
```

```sh
$ bundle install
$ bundle exec spring
You've tried to invoke Spring when it's already loaded (i.e. the Spring constant is defined).

This is probably because you generated binstubs with Spring 1.0, and you now have a Spring version > 1.0 on your system. To solve this, upgrade your bundle to the latest Spring version and then run `bundle exec spring binstub --all` to regenerate your binstubs. This is a one-time step necessary to upgrade from 1.0 to 1.1.

Here's the backtrace:

/home/user/bundle/ruby/2.3.0/bin/spring:22:in `load'
/home/user/bundle/ruby/2.3.0/bin/spring:22:in `<top (required)>'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/user/.gem/ruby/2.3.3/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/home/user/.gem/ruby/2.3.3/bin/bundle:22:in `load'
/home/user/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'
```

**Comment by vanboom** [comment]
Possibly related:  spring 1.7.2, Gemfile uses `github` method to get some gems...
I get the  `<gem...> is not yet checked out. Run `bundle install` first. (Bundler::GitError)` message unless I leave a terminal window open after running `bundle exec spring` in the terminal window.  Binstubs have been created and updated.  I find myself constantly having to use `bundle exec rake ... `, `bundle exec rails c` etc.  which defeats the point of spring.
