### ISSUE TITLE
undefined method `first' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by giacomo-giovenzana** [rails/spring#564]
When I run "rails console" I get the following error:
`$ rails c
/usr/lib/ruby/vendor_ruby/sprockets/digest_utils.rb:47: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/vendor_ruby/sprockets/digest_utils.rb:51: warning: constant ::Bignum is deprecated
/usr/lib/ruby/vendor_ruby/sprockets/processor_utils.rb:110: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/vendor_ruby/sprockets/processor_utils.rb:111: warning: constant ::Bignum is deprecated
/usr/lib/ruby/vendor_ruby/builder/xchar.rb:111: warning: constant ::Fixnum is deprecated
Traceback (most recent call last):
-e: undefined method `first' for nil:NilClass (NoMethodError)`

I have tried to restart spring by
`bin/spring stop`
or by a kill -9 command on pid.

Then, trying to re-run the same command I get the following:
`$ rails c
^CTraceback (most recent call last):
	16: from bin/rails:3:in `<main>'
	15: from bin/rails:3:in `load'
	14: from /home/adb/Dev/My/Rails/insalute/bin/spring:15:in `<top (required)>'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	11: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	10: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	 9: from /var/lib/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	 8: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	 7: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	 6: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:24:in `call'
	 5: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	 4: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/run.rb:35:in `call'
	 3: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/run.rb:42:in `warm_run'
	 2: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/run.rb:62:in `run'
	 1: from /var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/run.rb:117:in `verify_server_version'
/var/lib/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/run.rb:117:in `gets': Interrupt`

Rails command remains hanged and no message is shown. When I press Ctrl+C I get this error.

I have already tryed to uninstall and install spring but it does not solve.

I am using rails 5.1.1 and ruby 2.5.1.
I have googled the issue but I didn't find any useful solution.
Honestly, I don't know if it could be an issue of spring.

**Comment by djah79** [comment]
I have the same problem too
