### ISSUE TITLE
`verify_server_version': undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by plentz** [rails/spring#590]
```
WARNING: V8 isolate was forked, it can not be disposed and memory will not be reclaimed till the Ruby process exits.
Traceback (most recent call last):
	15: from bin/rails:3:in `<main>'
	14: from bin/rails:3:in `load'
	13: from /Users/plentz/src/github.com/xxx/xxx/bin/spring:20:in `<top (required)>'
	12: from /opt/rubies/2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /opt/rubies/2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	 9: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	 8: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	 7: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	 6: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	 5: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/rails.rb:24:in `call'
	 4: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	 3: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/run.rb:35:in `call'
	 2: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/run.rb:42:in `warm_run'
	 1: from /Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/run.rb:62:in `run'
/Users/plentz/.gem/ruby/2.5.5/gems/spring-2.0.2/lib/spring/client/run.rb:117:in `verify_server_version': undefined method `chomp' for nil:NilClass (NoMethodError)
```

**Comment by MarcSteven** [comment]
I also met this weird issue  

`Warning:[rake --tasks] /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:117:in `verify_server_version': undefined method `chomp' for nil:NilClass (NoMethodError)
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:62:in `run'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:58:in `cold_run'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:33:in `rescue in call'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:30:in `call'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/spring:15:in `require'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/spring:15:in `<top (required)>'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/rake:3:in `load'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/rake:3:in `<main>'
/Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:26:in `initialize': No such file or directory - connect(2) for /private/var/folders/fd/g2bjwxln7t12740h9w8pc1p40000gn/T/RMSpring/42e6a0595fd27398c1ded4ec95f50c14 (Errno::ENOENT)
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:26:in `open'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:26:in `connect'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/run.rb:31:in `call'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	from /Users/MarcZhao/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/spring:15:in `require'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/spring:15:in `<top (required)>'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/rake:3:in `load'
	from /Users/MarcZhao/Desktop/MemoryChain/MemoryChainWeb/bin/rake:3:in `<main>'`

**Comment by curi** [comment]
I had this problem when running `rails console`. I stopped my `rails server` that was running, and then `rails console` worked again. Hope that helps someone.
