### ISSUE TITLE
Spring + RSpec + Zeitwerk: reloading is disabled because config.cache_classes is true (RuntimeError)

### ISSUE THREAD

**Issue by pjmartorell** [rails/spring#598]
```
/Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies/zeitwerk_integration.rb:14:in `rescue in block in clear': reloading is disabled because config.cache_classes is true (RuntimeError)
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies/zeitwerk_integration.rb:12:in `block in clear'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:47:in `block in unload_interlock'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:20:in `block in unloading'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:19:in `unloading'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:47:in `unload_interlock'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies/zeitwerk_integration.rb:11:in `clear'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/application/finisher.rb:206:in `block (2 levels) in <module:Finisher>'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/application/finisher.rb:232:in `block (3 levels) in <module:Finisher>'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:120:in `class_unload!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0/lib/rails/application/finisher.rb:231:in `block (2 levels) in <module:Finisher>'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `instance_exec'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `block in make_lambda'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:606:in `catch'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:606:in `block in default_terminator'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:202:in `block in halting'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `block in invoke_before'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `each'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `invoke_before'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:134:in `run_callbacks'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:111:in `run!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:114:in `run!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:53:in `block (2 levels) in reload!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:52:in `tap'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:52:in `block in reload!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/reloader.rb:51:in `reload!'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:168:in `serve'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/pere/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```
It happens with Rails 6.0  and Spring 2.1.0 when I run RSpec in test environment with cache_classes=true and when I have modified a file. After the crash I run it again and it works.

**Comment by matpowel** [comment]
Having the exact same error with essentially the same call stack in Rails 6 (production release) + Minitest.

It seems like a legit complaint on the Rails / Zeitwerk side too if you look at the stack, Spring is clearly calling reload! and Zeitwerk is complaining that it won't do that because cache_classes is true.

**Comment by pjmartorell** [comment]
yes! I finally removed Spring from my tests binstub.

**Comment by matpowel** [comment]
FWIW we've just moved away from Spring for now, seems like it's too fragile in Rails 6

**Comment by pjmartorell** [comment]
I'm using it in development and I didn't have any problem so far.

**Comment by rafaelfranca** [comment]
If you want to use spring in the test environment you need to set `cache_classes` to false. The `rails new` command for 6.0 already set the correct value.

**Comment by Fjan** [comment]
@rafaelfranca  Setting `cache_classes` to false slows down the tests by about 15% (for us). Depending on the app this may be more than what you gain by using spring, but for large test suites it would seem better to set it to true and switch off spring. 

I'm not sure I understand why the performance impact should be that big, or if something can be done to improve it, but perhaps a workaround could be for spring to detect the cache_classes setting and then reload itself rather than crashing.

**Comment by Fjan** [comment]
Come to think of it, what you really want is `cache_classes` set to false when you are running single tests, so spring can help you by keeping the app in memory, but you want `cache_classes` set to true when running the entire suite so it's faster. The only way I can think of achieving that is by creating a second test environment and patch the test commands to use the optimal one for the situation. That's clumsy. Any better ideas?

**Comment by dogweather** [comment]
I'm interested in the documentation of this "gotcha". I understand the behavior, and the fix to properly set `cache_classes`. But this is non-obvious. 

Could we re-consider opening this issue to document the setting, and its effects in test?

**Comment by trkoch** [comment]
To anybody interested to speed up CI runs, this is what I added to `config/environments/test.rb`

```rb
config.cache_classes = ENV['RAILS_CACHE_CLASSES'] == 'TRUE'
```

To explicitly run tests with class caching enabled, I run `RAILS_CACHE_CLASSES=TRUE bin/rspec`. Obviously this fails when a (Ruby) file is changed during the test run, or tests are run multiple times and a file changed in the meantime. This is not very common in a typically ephemeral CI environment though.

**Comment by inner-whisper** [comment]
Just a little upgrade for https://github.com/rails/spring/issues/598#issuecomment-682046748 comment:

```ruby
config.cache_classes = ENV["CI"].present?
```

`CI` environment variable is a default for continuous integration services, so we need no additional ones.

P.S> Of course, for whole test suite run on local machine it's better to have separate env var, like `RAILS_CACHE_CLASSES`.
