### ISSUE TITLE
rails master with spring master fails to start

### ISSUE THREAD

**Issue by scottjg** [rails/spring#613]
```
$ /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-c1ccc6a0d240/activesupport/lib/active_support/fork_tracker.rb:8:in `fork': super: no superclass method `fork' for #<Spring::Application:0x00007fd8888563e0> (NoMethodError)
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/scottjg/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

**Comment by hahmed** [comment]
What platform are you using? 

Perhaps this is relevant? https://github.com/rails/spring#compatibility

**Comment by scottjg** [comment]
sorry.. unclear what changed exactly but i upgraded ruby on my system and the problem went away.
