### ISSUE TITLE
Support for gems.rb is causing a NameError for the `Bundler` constant in generators

### ISSUE THREAD

**Issue by elia** [rails/spring#624]
The use of `Bundler` in https://github.com/rails/spring/pull/588 is causing:

```
foo-app:master $ cd /tmp/foo-app/; spring stop; trash tmp/cache/boot*; bin/rails g -h                                                                                                 /t/foo-app
Spring stopped.
fish: No matches for wildcard 'tmp/cache/boot*'. See `help expand`.
cd /tmp/foo-app/; spring stop; trash tmp/cache/boot*; bin/rails g -h
                                       ^
/Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/configuration.rb:8:in `gemfile': uninitialized constant #<Class:Spring>::Bundler (NameError)
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/configuration.rb:47:in `find_project_root'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/configuration.rb:41:in `project_root_path'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/configuration.rb:32:in `application_root_path'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:288:in `loaded_application_features'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:119:in `ensure in preload'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:126:in `preload'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /Users/elia/.asdf/installs/ruby/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'
```

The app comes from a vanilla `rails new` plus `solidus` added to the gemfile (I was testing a generator).
I think it just needs to require Bundler where it's used. Locally I solved by downgrading to v2.1.0.

**Comment by Sixeight** [comment]
[Forked process](https://github.com/rails/spring/blob/a85d32ef3726931b2b81abbb10a6e1c2964e7e32/lib/spring/application_manager.rb#L98-L111) doesn't know Bundler. Then [`ProcessTitleUpdater` on boot.rb](https://github.com/rails/spring/blob/a85d32ef3726931b2b81abbb10a6e1c2964e7e32/lib/spring/application/boot.rb#L15) failed to update process title because `app.app_name` [uses `Bundler.default_gemfile` through `Spring.gemfile`](https://github.com/rails/spring/blob/a85d32ef3726931b2b81abbb10a6e1c2964e7e32/lib/spring/configuration.rb#L11) .

```
Spring is running:

57589 spring server | sample | started 29 secs ago
57590 ruby -I /Users/tomohiro/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib -e require 'spring/application/boot'
```

I except

```
Spring is running:

55038 spring server | sample | started 8 secs ago
55040 spring app    | sample | started 8 secs ago | development mode
```

**Comment by alexbel** [comment]
Look like the PR is not going to merged any time soon.
Workaround: add  `require 'bundler'` in `~/.spring.rb`
