### ISSUE TITLE
using spring does not work from subdirectories

### ISSUE THREAD

**Issue by ccutrer** [rails/spring#644]
having a rails project with a spec directory:

```cd spec
spring rspec lib/acts_as_list_spec.rb
>> Spring was unable to find your config/application.rb file. Your project root was detected at /Users/cody/src/canvas-lms/spec, so Spring looked for /Users/cody/src/canvas-lms/spec/config/application.rb but it doesn't exist. You can configure the root of your application by setting Spring.application_root in config/spring.rb.
```

But non-springified works fine, properly searching the parent dir for the Gemfile, and then booting the app.

I've explored this quite a bit by monkey patching, and even if you can get the Spring client to boot via enough tricks, the server will still try to launch from the wrong directory and throw the same error. If you're sneaky and boot the server from the actual project root, and then run `spring rspec` from the spec directory, it will not have the some working directory, and just be confusing. It seems like the server needs to be directory aware - having the client pass its working directory through, and the server changing to that before running the command.

**Comment by ccutrer** [comment]
Note that getting this working would almost certainly open avenues for proper spring usage from the dummy app of an engine, or the reverse case - from within an engine embedded in a larger app, or the spring binstub being a symlink (again, from an engine embedded in a larger app)

**Comment by deivid-rodriguez** [comment]
This could be the regression in 2.1.1. Can you try either the latest code in the master branch, or 2.1.0?

**Comment by JuPlutonic** [comment]
Yes, using spring (2.1.0) **the error** disappeared:
<details>
<summary>...</summary>
 <pre>
Traceback (most recent call last):
	3: from ./bin/spring:19:in `<main>'
	2: from /home/X/dotfiles/common/.anyenv/envs/rbenv/versions/2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
	1: from /home/X/dotfiles/common/.anyenv/envs/rbenv/versions/2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
/home/X/dotfiles/common/.anyenv/envs/rbenv/versions/2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'spring' (= 2.1.1) - did find: [spring-2.1.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/ /dotfiles/common/.anyenv/envs/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0:/home/alessio/.gem/ruby/2.6.0' , execute `gem env` for more information
</pre>
</details>

**Comment by chriscz** [comment]
I ran a bisect against spring (v2.0.0 to master) with a new rails 6.1 app but I was unable to find a good commit where the error message doesn't come up.

Here's the test code: https://github.com/chriscz/spring-nested-bug

**Comment by JuPlutonic** [comment]
I did installation of spring.2.1.1 [master](https://github.com/rails/spring/commit/577cf01f232bb6dbd0ade7df2df2ac209697e741)
And with it (pkg/spring-2.1.1.gem) inside canvas-lms application also got:
`Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)`

**Comment by deivid-rodriguez** [comment]
Then that's not the culprit :(. The repro posted should be very helpful for anyone wanting to investigate the issue :+1:.

**Comment by chriscz** [comment]
The bug is in the `spring/configuration.rb` code that uses `gemfile` which returns an absolute path to the Gemfile (at least in Bundler 2.2.14). Joining an absolute path with any other path always returns the absolute path and so the `exists?` check succeeds. 

https://github.com/rails/spring/blob/577cf01f232bb6dbd0ade7df2df2ac209697e741/lib/spring/configuration.rb#L46-L54

I'm not entirely sure what the best fix would be, but maybe one of the following:
1. checking whether the Gemfile is absolute and checking that `config/application.rb` exists and returning that directory?
```ruby
    def find_project_root(current_dir)
      if gemfile.absolute? && gemfile.dirname.join('config/application.rb').exist?
        return gemfile.dirname
      end

      if current_dir.join(gemfile).exist?
        current_dir
      elsif current_dir.root?
        raise UnknownProject.new(Dir.pwd)
      else
        find_project_root(current_dir.parent)
      end
    end
```
2. Otherwise we could try just walking up the current path to find the first one that defines `config/application.rb`? 
```ruby
    def find_project_root(current_dir)
      if current_dir.join('config/application.rb').exist?
        current_dir
      elsif current_dir.root?
        raise UnknownProject.new(Dir.pwd)
      else
        find_project_root(current_dir.parent)
      end
    end
```
3. To support engines as well we could just walk up the tree and find the first directory that contains a `Gemfile.lock`
```ruby
    def find_project_root(current_dir)
      if current_dir.join('Gemfile.lock').exist?
        current_dir
      elsif current_dir.root?
        raise UnknownProject.new(Dir.pwd)
      else
        find_project_root(current_dir.parent)
      end
    end
```

Any other ideas?

I can submit a PR if you are happy with any of these proposals.

**Comment by deivid-rodriguez** [comment]
Just to make it clear, I don't maintain this repo. I just noticed this issue and thought the pointer to the regression in 2.1.1 could be helpful.

**Comment by JuPlutonic** [comment]
@chriscz my coin: 3rd needs to be much more complex:
```ruby
if current_dir.sub_ext(current_dir.to_s =~ /\bgems\.rb\z/ ? '.locked' : '.lock').exist?
```

**Comment by chriscz** [comment]
Come to think of it, just looking for Gemfile + application config sounds like a good solution @JuPlutonic,  should actually work for the dummy-app case as well.

**Comment by sdcorey** [comment]
I ran across this recently as well.  It's only a minor annoyance for our purposes.  All the above discussion holds regarding the cause:  Spring::gemfile is returning a fully qualified pathname, and Spring::find_project_root, which recurses the directory tree looking for project root, is expecting the basename only -- no path.  Spring::gemfile also contains special code to handle ruby 1.9.x which will cause a failure (with a different message) if the CWD is anything other than project root.  All code is contained in "spring/lib/spring/configuration.rb".

It seems some options are:

A.  Drop support for starting spring in a directory other than project root.  Fail with a meaningful error if this is attempted.  Spring#find_project_root goes away.

B.  Create Spring::gemfile_basename which returns the correct gemfile basename for 1.9.x and other versions.  This is clearly what the current implementation of Spring#find_project_root is expecting in order to work.  This keeps Spring::gemfile from being referenced in the recursion loop.  Once the recursion is complete, Spring::gemfile can then use the found project root to provide a correct gemfile path for other parts of the code that rely on it.

C.  Drop support for ruby 1.9.x and trust Bundler::default_gemfile to find the root path for us if indeed it does so robustly across its intended compatible versions.  Spring#find_project_root goes away.
