### ISSUE TITLE
spring 4.0.0 gets hanged with rails 6.1

### ISSUE THREAD

**Issue by siddhant-mohan** [rails/spring#673]
rails c gets stuck on local. 

Ruby version: 3.1.0 (same on 3.0.0)

Rails version : 6.1.4

Spring version: 4.0.0 (same on 3.1.0)

Stack trace
```
s$ rails c
^C/Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/run.rb:117:in `gets': Interrupt
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/run.rb:117:in `verify_server_version'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/run.rb:62:in `run'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/run.rb:42:in `warm_run'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/run.rb:35:in `call'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/rails.rb:24:in `call'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
	from /Users/s/.rvm/gems/ruby-3.1.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/s/Projects/flinket/moneycapital/bin/spring:10:in `require'
	from /Users/s/Projects/flinket/moneycapital/bin/spring:10:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /Users/s/Projects/flinket/moneycapital/bin/spring:7:in `<top (required)>'
	from bin/rails:2:in `load'
	from bin/rails:2:in `<main>'
```

**Comment by siddhant-mohan** [comment]
https://github.com/rails/spring/issues/668

**Comment by rafaelfranca** [comment]
Duplicated of #663
